-- ============================================================================
-- Earnings reliability — expanded universe.
--
-- Intentionally a no-op in this repo. This step only loaded rows into
-- earnings_reliability, and those rows are produced externally (see the
-- "Research boundary" section of the README). The file is kept so the applied
-- migration chain stays contiguous against an existing database.
-- ============================================================================
